---
title: "p8105_hw2_mk4996"
author: "Miho Kawanami"
date: "2025-09-27"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Problem 1

## First: Cleaning the data in pols-month.csv.
```{r}
library(tidyverse)

pols_df = read_csv(file = "./pols-month.csv",
                         na = c(".", "NA", "")) |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = factor(month.name[month], levels = month.name, ordered = TRUE),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem",
      TRUE ~ NA_character_
    )) |>
  select(-day, -prez_dem, -prez_gop)

  head(pols_df)
```

## Second: Cleaning the data in snp.csv.
```{r}
snp_df = read_csv(file = "./snp.csv",
                         na = c(".", "NA", "")) |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) |>
  mutate(
  year = ifelse(year < 20, year + 2000, year + 1900),  
  month = factor(month.name[month], levels = month.name, ordered = TRUE)) |>
  select(year, month, close) |>
  arrange(year, month)

  head(snp_df)
```

## Third: Tidying the unemployment data
```{r}
unemp_df = read_csv(file = "./unemployment.csv",
                         na = c(".", "NA", "")) |>
  janitor::clean_names() |>
  pivot_longer(-year, names_to = "month", values_to = "unemployment") |>
  mutate(
    month = match(tolower(month), tolower(month.abb)),
    month = factor(month.name[month], levels = month.name, ordered = TRUE)
  ) |>
  arrange(year, month)

  head(unemp_df)

```
